/**
 * Author Stephanos B
 * Date 8/01/2026
 */
package gui.views;

import gui.navigator.AppNavigator;
import gui.state.AppState;
import gui.components.GameTile;
import core.managers.GameManager;
import core.objects.Game;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;

public class GameLibraryView extends BaseView {
    // UI Components (from your JForm design)
    private JScrollPane scrollPane;

    // Custom components
    private JPanel gameTilesPanel; // Will be inside scrollPane

    public GameLibraryView(AppNavigator navigator, Map<String, Object> params) {
        super(navigator, params);
    }

    @Override
    protected void initializeUI() {
        // Initialize JForm components
        initComponents();

        // Use the designed layout from JForm
        setLayout(new BorderLayout());
        add(scrollPane, BorderLayout.CENTER);

        // Create panel for game tiles (inside scroll pane)
        gameTilesPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 20));
        gameTilesPanel.setBackground(Color.WHITE);
        scrollPane.setViewportView(gameTilesPanel);
    }

    @Override
    protected void initializeData() {
        loadGameTiles();
    }

    private void loadGameTiles() {
        gameTilesPanel.removeAll();

        // 1. ADD "ADD GAME" TILE (always first)
        GameTile addTile = new GameTile(); // Constructor with no args = add button
        addTile.addTileClickListener(e -> {
            navigator.navigateTo("addGame");
        });
        gameTilesPanel.add(addTile);

        // 2. Try to get games
        List<Game> games;
        try {
            games = GameManager.getAllGames();
        } catch (Exception e) {
            showError("Failed to load games: " + e.getMessage());
            games = addSampleGames(); // Fallback
        }
        // Add game tiles from whatever populated the game list
        for (Game game : games) {
            addGameTile(game);
        }

        // Refresh display
        gameTilesPanel.revalidate();
        gameTilesPanel.repaint();
    }

    private void addGameTile(Game game) {
        GameTile tile = new GameTile(game.getId(), game.getName());

        // Click on tile -> set current game and navigate
        tile.addTileClickListener(e -> {
            AppState.getInstance().setCurrentGame(game);
            navigator.navigateTo("modManager",
                    Map.of("gameId", game.getId()));
        });

        // Edit button -> set current game and navigate to editor
        tile.addEditButtonListener(e -> {
            AppState.getInstance().setCurrentGame(game);
            navigator.navigateTo("editGame",
                    Map.of("gameId", game.getId()));
        });

        gameTilesPanel.add(tile);
    } // addGameTile()

    private List<Game> addSampleGames() {
        // Remove this in production - just for demo
        return Arrays.asList(
                createSampleGame("ghost-recon", "Ghost Recon Breakpoint"),
                createSampleGame("cyberpunk2077", "Cyberpunk 2077"),
                createSampleGame("skyrim-se", "Skyrim Special Edition"),
                createSampleGame("witcher3", "The Witcher 3"),
                createSampleGame("fallout4", "Fallout 4"));
    }

    private Game createSampleGame(String id, String name) {
        // Create a simple game object for demo
        // Replace with your actual Game constructor
        Game game = new Game();
        game.setId(id);
        game.setName(name);
        return game;
    }

    /**
     * JForm-generated initialization.
     * COPY FROM YOUR GameLibraryPanel.java
     */
    private void initComponents() {
        // ======== Generated by JFormDesigner ========
        scrollPane = new JScrollPane();

        // ======== this ========
        setMinimumSize(new Dimension(200, 250));
        setPreferredSize(new Dimension(400, 400));

        // ======== scrollPane ========
        {
            scrollPane.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            scrollPane.setMinimumSize(new Dimension(80, 80));
        }
    }
} // Class