%% Author: Stephanos B
%% Date: 24/12/2025
flowchart TD
    
    Start(Remove ModFile of trashed Mod Logic:)
    --> ReadLineage[Read File Lineage]
        %% This Mod is being removed, therefore they forefit any Ownership.
    --> RemoveFromLineage[Remove all of Mod from Lineage]
    --> IsLastOwner{If Stack is empty?}
    IsLastOwner -- No
        -->CopyTrash[COPY file to trash<br>Retain file]
        --> CheckHash{If Mod Hash matches File?}
    IsLastOwner -- Yes<br>(no other owners)
        --> TrashFile[MOVE current File to Trash]
        --> TrashLineage[Trash empty Lineage]
        --> Clean[Try clean empty directories]

    CheckHash -- Yes<br>(identical, no change)
        %% If the file is the same as the new Owner expects, then there is no reason to change it.
        --> UpdateLineage[Update Lineage]
    CheckHash -- No<br>(restore file)
        %% File is different to what the new Owner expects. Must restore to their version...
        --> IfGameOwned{If new Owner is GAME?}
        IfGameOwned -- Yes
            --> RestoreFromBackup[OVERRIDE file from GAME backup]
            --> UpdateLineage
        IfGameOwned -- No
            --> RestoreFromManifest[OVERRIDE file from Mod Owner]
            --> UpdateLineage

    Clean --> End
    UpdateLineage --> End(File removed safely!)

%% SubGraphs
    subgraph Legend
        IO_OP(IO operation)
        Stack_OP(Stack operation)
        FileS_OP(FileSystem operation)
    end

%% Styles
    style Start color:#FFFFFF, fill:#00C853, stroke:#00C853
    style End color:#FFFFFF, fill:#e3223b, stroke:#930013
    
    style IO_OP color:#FFFFFF, fill:#ea38bc, stroke:#980d74
    style ReadLineage color:#FFFFFF, fill:#ea38bc, stroke:#980d74
    style UpdateLineage color:#FFFFFF, fill:#ea38bc, stroke:#980d74

    style Stack_OP color:#FFFFFF, fill:#2ab388, stroke:#26775e
    style RemoveFromLineage color:#FFFFFF, fill:#2ab388, stroke:#26775e
    
    style FileS_OP color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style TrashFile color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style TrashLineage color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style CopyTrash color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style RestoreFromBackup color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style RestoreFromManifest color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style Clean color:#FFFFFF, fill:#2962FF, stroke:#0b42d6