%% Author: Stephanos B
%% Date: 24/12/2025
flowchart TD
    
    Start(Remove ModFile of trashed Mod Logic:)
    --> CheckLineage{If lineage exsists?} -- No --> Error[Error: This should not occur!]

    CheckLineage -- Yes
        --> ReadLineage[Read File Lineage]
            %% This Mod is being removed, therefore they forefit any Ownership.
        --> RemoveFromLineage[Remove all of Mod from Lineage]
        --> PeekLineageStack[Peek the latest owner in Lineage]
        --> CheckHash{If Mod Hash matches File}

        CheckHash -- Yes<br>Identical, no change.
        %% If the file is the same as the new Owner expects, then there is no reason to change it.
            --> CleanDirectories[Try clean empty directories.]
            --> UpdateLineage
        CheckHash -- No
        %% File is different to what the new Owner expects. Must restore to their version...
            --> TrashFile[Move current File to Trash]
            --> IfGameOwned{If new Owner is GAME}
                IfGameOwned -- Yes
                    --> RestoreFromBackup[Override file from GAME backup]
                    --> UpdateLineage
                IfGameOwned -- No
                    --> RestoreFromManifest[Override file from Mod Owner]
                    --> UpdateLineage

        UpdateLineage[Update Lineage]
        --> End(File removed safely!)

%% SubGraphs
    subgraph Legend
        IO_OP(IO operation)
        Stack_INIT(Stack INIT) --> Stack_OP(Stack operation)
        FileS_OP(FileSystem operation)
    end

%% Styles
    style Start color:#FFFFFF, fill:#00C853, stroke:#00C853
    style End color:#FFFFFF, fill:#e3223b, stroke:#930013
    
    style IO_OP color:#FFFFFF, fill:#ea38bc, stroke:#980d74
    style ReadLineage color:#FFFFFF, fill:#ea38bc, stroke:#980d74
    style UpdateLineage color:#FFFFFF, fill:#ea38bc, stroke:#980d74

    
    style Stack_INIT color:#FFFFFF, fill:#17ae63, stroke:#0b7f45
    style Stack_OP color:#FFFFFF, fill:#2ab388, stroke:#26775e
    style RemoveFromLineage color:#FFFFFF, fill:#2ab388, stroke:#26775e
    
    style FileS_OP color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style TrashFile color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style RestoreFromBackup color:#FFFFFF, fill:#2962FF, stroke:#0b42d6
    style RestoreFromManifest color:#FFFFFF, fill:#2962FF, stroke:#0b42d6